language: cpp
compiler:
  - gcc
#  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.7 g++-4.7
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y libtbb-dev
cache: apt
script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
  - autoreconf --install && ./configure && make
