language: cpp

compiler:
  - gcc
#  - clang
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo apt-get install -y libtbb-dev
  - wget --no-verbose --output-document=boost-trunk.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2/download
  - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost-trunk"
  - export CMAKE_MODULE_PATH="$BOOST_ROOT"
  - mkdir -p $BOOST_ROOT
  - tar jxf boost-trunk.tar.bz2 --strip-components=1 -C $BOOST_ROOT

install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - cd $BOOST_ROOT && ./bootstrap.sh --with-libraries=serialization,program_options,filesystem,system,regex,test
  - cd $BOOST_ROOT && ./b2 threading=multi --prefix=$BOOST_ROOT -d0 install

script:
  - autoreconf --install && ./configure --with-boost=$BOOST_ROOT && make


cache:
  # directory:
  #   - $BOOST_ROOT
  - apt