language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: autoreconf --install && ./configure && make
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev
