language: cpp
compiler:
  - gcc
#  - clang
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.7 g++-4.7
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo apt-get install -y libboost1.54-all-dev
  - sudo apt-get install -y libtbb-dev
#cache: apt
script:
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
- autoreconf --install && ./configure && make
# - make clean
#  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
#  - gcc --version && g++ --version
#  - autoreconf --install && ./configure && make
